# Generated by Django 3.0.3 on 2021-06-28 14:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proweb_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='', max_length=100, null=True)),
                ('code', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('cname', models.CharField(default='', max_length=100, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('is_display', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'proweb_code',
            },
        ),
        migrations.CreateModel(
            name='proweb_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('serial_code', models.CharField(default='', max_length=2, null=True)),
                ('serial_num', models.IntegerField(default=0, null=True)),
                ('serial', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('author', models.CharField(default='', max_length=255, null=True)),
                ('office', models.CharField(default='', max_length=255, null=True)),
                ('publish', models.DateField(blank=True, default='', null=True)),
                ('price', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', ckeditor_uploader.fields.RichTextUploadingField()),
                ('click', models.IntegerField(default=0)),
                ('is_delete', models.IntegerField(default=0)),
                ('is_display', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default='', null=True)),
                ('modify_time', models.DateTimeField(default='', null=True)),
            ],
            options={
                'db_table': 'proweb_product',
            },
        ),
    ]
