# Generated by Django 3.0.3 on 2021-06-30 17:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proweb_product',
            name='category',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
