# Generated by Django 2.2.5 on 2021-06-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proweb_code',
            old_name='type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='proweb_product',
            old_name='type',
            new_name='types',
        ),
    ]
