# Generated by Django 3.0.3 on 2021-06-30 17:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210630_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proweb_product',
            name='category',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
