# Generated by Django 2.2.5 on 2021-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proweb_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=150)),
                ('name', models.CharField(default='', max_length=30)),
                ('sex', models.IntegerField(default='', null=True)),
                ('birthday', models.DateField(default='', null=True)),
                ('email', models.EmailField(default='', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default='', null=True)),
                ('modify_time', models.DateTimeField(default='', null=True)),
            ],
            options={
                'db_table': 'proweb_user',
            },
        ),
    ]
