# Generated by Django 3.0.3 on 2021-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proweb_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('file_name', models.CharField(default='', max_length=255, unique=True)),
                ('path', models.CharField(default='', max_length=255, null=True)),
                ('size', models.CharField(default='', max_length=30, null=True)),
                ('types', models.CharField(default='', max_length=30, null=True)),
            ],
            options={
                'db_table': 'proweb_file',
            },
        ),
        migrations.CreateModel(
            name='proweb_file_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(default=0)),
                ('data_type', models.CharField(default='', max_length=100, null=True)),
                ('file_id', models.IntegerField(default=0)),
                ('create_by', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default='', null=True)),
                ('modify_by', models.IntegerField(default=0)),
                ('modify_time', models.DateTimeField(default='', null=True)),
            ],
            options={
                'db_table': 'proweb_file_data',
            },
        ),
        migrations.CreateModel(
            name='proweb_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('short_link', models.CharField(default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('sex', models.IntegerField(default=1, null=True)),
                ('birthday', models.DateField(blank=True, default='', null=True)),
                ('phone', models.CharField(default='', max_length=10, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('file_id', models.IntegerField(default=0)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default='', null=True)),
                ('modify_time', models.DateTimeField(default='', null=True)),
            ],
            options={
                'db_table': 'proweb_user',
            },
        ),
    ]
