# Generated by Django 2.2.5 on 2021-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proweb_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='', max_length=100, null=True)),
                ('code', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('cname', models.CharField(default='', max_length=100, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('is_display', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'proweb_code',
            },
        ),
    ]
