# Generated by Django 2.2.5 on 2021-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proweb_file',
            name='file_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
