# Generated by Django 2.2.5 on 2021-07-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_proweb_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proweb_file',
            name='file_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='proweb_file_data',
            table='proweb_file_data',
        ),
    ]
